// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializeapexInfo")
public inline fun apexInfo(block: chromeos_update_engine.ApexInfoKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.ApexInfo =
  chromeos_update_engine.ApexInfoKt.Dsl._create(chromeos_update_engine.UpdateMetadata.ApexInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * Definition has been duplicated from
 * $ANDROID_BUILD_TOP/build/tools/releasetools/ota_metadata.proto. Keep in sync.
 * ```
 *
 * Protobuf type `chromeos_update_engine.ApexInfo`
 */
public object ApexInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.ApexInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.ApexInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.ApexInfo = _builder.build()

    /**
     * `optional string package_name = 1;`
     */
    public var packageName: kotlin.String
      @kotlin.jvm.JvmName("getPackageName")
        get() = _builder.packageName
      @kotlin.jvm.JvmName("setPackageName")
        set(value) {
        _builder.packageName = value
      }
    /**
     * `optional string package_name = 1;`
     */
    public fun clearPackageName() {
      _builder.clearPackageName()
    }
    /**
     * `optional string package_name = 1;`
     * @return Whether the packageName field is set.
     */
    public fun hasPackageName(): kotlin.Boolean {
      return _builder.hasPackageName()
    }

    /**
     * `optional int64 version = 2;`
     */
    public var version: kotlin.Long
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `optional int64 version = 2;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
    /**
     * `optional int64 version = 2;`
     * @return Whether the version field is set.
     */
    public fun hasVersion(): kotlin.Boolean {
      return _builder.hasVersion()
    }

    /**
     * `optional bool is_compressed = 3;`
     */
    public var isCompressed: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsCompressed")
        get() = _builder.isCompressed
      @kotlin.jvm.JvmName("setIsCompressed")
        set(value) {
        _builder.isCompressed = value
      }
    /**
     * `optional bool is_compressed = 3;`
     */
    public fun clearIsCompressed() {
      _builder.clearIsCompressed()
    }
    /**
     * `optional bool is_compressed = 3;`
     * @return Whether the isCompressed field is set.
     */
    public fun hasIsCompressed(): kotlin.Boolean {
      return _builder.hasIsCompressed()
    }

    /**
     * `optional int64 decompressed_size = 4;`
     */
    public var decompressedSize: kotlin.Long
      @kotlin.jvm.JvmName("getDecompressedSize")
        get() = _builder.decompressedSize
      @kotlin.jvm.JvmName("setDecompressedSize")
        set(value) {
        _builder.decompressedSize = value
      }
    /**
     * `optional int64 decompressed_size = 4;`
     */
    public fun clearDecompressedSize() {
      _builder.clearDecompressedSize()
    }
    /**
     * `optional int64 decompressed_size = 4;`
     * @return Whether the decompressedSize field is set.
     */
    public fun hasDecompressedSize(): kotlin.Boolean {
      return _builder.hasDecompressedSize()
    }
  }
}
public inline fun chromeos_update_engine.UpdateMetadata.ApexInfo.copy(block: `chromeos_update_engine`.ApexInfoKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.ApexInfo =
  `chromeos_update_engine`.ApexInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

