// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializedeltaArchiveManifest")
public inline fun deltaArchiveManifest(block: chromeos_update_engine.DeltaArchiveManifestKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.DeltaArchiveManifest =
  chromeos_update_engine.DeltaArchiveManifestKt.Dsl._create(chromeos_update_engine.UpdateMetadata.DeltaArchiveManifest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `chromeos_update_engine.DeltaArchiveManifest`
 */
public object DeltaArchiveManifestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.DeltaArchiveManifest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.DeltaArchiveManifest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.DeltaArchiveManifest = _builder.build()

    /**
     * ```
     * (At time of writing) usually 4096
     * ```
     *
     * `optional uint32 block_size = 3 [default = 4096];`
     */
    public var blockSize: kotlin.Int
      @kotlin.jvm.JvmName("getBlockSize")
        get() = _builder.blockSize
      @kotlin.jvm.JvmName("setBlockSize")
        set(value) {
        _builder.blockSize = value
      }
    /**
     * ```
     * (At time of writing) usually 4096
     * ```
     *
     * `optional uint32 block_size = 3 [default = 4096];`
     */
    public fun clearBlockSize() {
      _builder.clearBlockSize()
    }
    /**
     * ```
     * (At time of writing) usually 4096
     * ```
     *
     * `optional uint32 block_size = 3 [default = 4096];`
     * @return Whether the blockSize field is set.
     */
    public fun hasBlockSize(): kotlin.Boolean {
      return _builder.hasBlockSize()
    }

    /**
     * ```
     * If signatures are present, the offset into the blobs, generally
     * tacked onto the end of the file, and the length. We use an offset
     * rather than a bool to allow for more flexibility in future file formats.
     * If either is absent, it means signatures aren't supported in this
     * file.
     * ```
     *
     * `optional uint64 signatures_offset = 4;`
     */
    public var signaturesOffset: kotlin.Long
      @kotlin.jvm.JvmName("getSignaturesOffset")
        get() = _builder.signaturesOffset
      @kotlin.jvm.JvmName("setSignaturesOffset")
        set(value) {
        _builder.signaturesOffset = value
      }
    /**
     * ```
     * If signatures are present, the offset into the blobs, generally
     * tacked onto the end of the file, and the length. We use an offset
     * rather than a bool to allow for more flexibility in future file formats.
     * If either is absent, it means signatures aren't supported in this
     * file.
     * ```
     *
     * `optional uint64 signatures_offset = 4;`
     */
    public fun clearSignaturesOffset() {
      _builder.clearSignaturesOffset()
    }
    /**
     * ```
     * If signatures are present, the offset into the blobs, generally
     * tacked onto the end of the file, and the length. We use an offset
     * rather than a bool to allow for more flexibility in future file formats.
     * If either is absent, it means signatures aren't supported in this
     * file.
     * ```
     *
     * `optional uint64 signatures_offset = 4;`
     * @return Whether the signaturesOffset field is set.
     */
    public fun hasSignaturesOffset(): kotlin.Boolean {
      return _builder.hasSignaturesOffset()
    }

    /**
     * `optional uint64 signatures_size = 5;`
     */
    public var signaturesSize: kotlin.Long
      @kotlin.jvm.JvmName("getSignaturesSize")
        get() = _builder.signaturesSize
      @kotlin.jvm.JvmName("setSignaturesSize")
        set(value) {
        _builder.signaturesSize = value
      }
    /**
     * `optional uint64 signatures_size = 5;`
     */
    public fun clearSignaturesSize() {
      _builder.clearSignaturesSize()
    }
    /**
     * `optional uint64 signatures_size = 5;`
     * @return Whether the signaturesSize field is set.
     */
    public fun hasSignaturesSize(): kotlin.Boolean {
      return _builder.hasSignaturesSize()
    }

    /**
     * ```
     * The minor version, also referred as "delta version", of the payload.
     * Minor version 0 is full payload, everything else is delta payload.
     * ```
     *
     * `optional uint32 minor_version = 12 [default = 0];`
     */
    public var minorVersion: kotlin.Int
      @kotlin.jvm.JvmName("getMinorVersion")
        get() = _builder.minorVersion
      @kotlin.jvm.JvmName("setMinorVersion")
        set(value) {
        _builder.minorVersion = value
      }
    /**
     * ```
     * The minor version, also referred as "delta version", of the payload.
     * Minor version 0 is full payload, everything else is delta payload.
     * ```
     *
     * `optional uint32 minor_version = 12 [default = 0];`
     */
    public fun clearMinorVersion() {
      _builder.clearMinorVersion()
    }
    /**
     * ```
     * The minor version, also referred as "delta version", of the payload.
     * Minor version 0 is full payload, everything else is delta payload.
     * ```
     *
     * `optional uint32 minor_version = 12 [default = 0];`
     * @return Whether the minorVersion field is set.
     */
    public fun hasMinorVersion(): kotlin.Boolean {
      return _builder.hasMinorVersion()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PartitionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Only present in major version >= 2. List of partitions that will be
     * updated, in the order they will be updated. This field replaces the
     * |install_operations|, |kernel_install_operations| and the
     * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
     * array can have more than two partitions if needed, and they are identified
     * by the partition name.
     * ```
     *
     * `repeated .chromeos_update_engine.PartitionUpdate partitions = 13;`
     */
     public val partitions: com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.PartitionUpdate, PartitionsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.partitionsList
      )
    /**
     * ```
     * Only present in major version >= 2. List of partitions that will be
     * updated, in the order they will be updated. This field replaces the
     * |install_operations|, |kernel_install_operations| and the
     * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
     * array can have more than two partitions if needed, and they are identified
     * by the partition name.
     * ```
     *
     * `repeated .chromeos_update_engine.PartitionUpdate partitions = 13;`
     * @param value The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPartitions")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.PartitionUpdate, PartitionsProxy>.add(value: chromeos_update_engine.UpdateMetadata.PartitionUpdate) {
      _builder.addPartitions(value)
    }
    /**
     * ```
     * Only present in major version >= 2. List of partitions that will be
     * updated, in the order they will be updated. This field replaces the
     * |install_operations|, |kernel_install_operations| and the
     * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
     * array can have more than two partitions if needed, and they are identified
     * by the partition name.
     * ```
     *
     * `repeated .chromeos_update_engine.PartitionUpdate partitions = 13;`
     * @param value The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPartitions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.PartitionUpdate, PartitionsProxy>.plusAssign(value: chromeos_update_engine.UpdateMetadata.PartitionUpdate) {
      add(value)
    }
    /**
     * ```
     * Only present in major version >= 2. List of partitions that will be
     * updated, in the order they will be updated. This field replaces the
     * |install_operations|, |kernel_install_operations| and the
     * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
     * array can have more than two partitions if needed, and they are identified
     * by the partition name.
     * ```
     *
     * `repeated .chromeos_update_engine.PartitionUpdate partitions = 13;`
     * @param values The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPartitions")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.PartitionUpdate, PartitionsProxy>.addAll(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.PartitionUpdate>) {
      _builder.addAllPartitions(values)
    }
    /**
     * ```
     * Only present in major version >= 2. List of partitions that will be
     * updated, in the order they will be updated. This field replaces the
     * |install_operations|, |kernel_install_operations| and the
     * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
     * array can have more than two partitions if needed, and they are identified
     * by the partition name.
     * ```
     *
     * `repeated .chromeos_update_engine.PartitionUpdate partitions = 13;`
     * @param values The partitions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPartitions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.PartitionUpdate, PartitionsProxy>.plusAssign(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.PartitionUpdate>) {
      addAll(values)
    }
    /**
     * ```
     * Only present in major version >= 2. List of partitions that will be
     * updated, in the order they will be updated. This field replaces the
     * |install_operations|, |kernel_install_operations| and the
     * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
     * array can have more than two partitions if needed, and they are identified
     * by the partition name.
     * ```
     *
     * `repeated .chromeos_update_engine.PartitionUpdate partitions = 13;`
     * @param index The index to set the value at.
     * @param value The partitions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPartitions")
    public operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.PartitionUpdate, PartitionsProxy>.set(index: kotlin.Int, value: chromeos_update_engine.UpdateMetadata.PartitionUpdate) {
      _builder.setPartitions(index, value)
    }
    /**
     * ```
     * Only present in major version >= 2. List of partitions that will be
     * updated, in the order they will be updated. This field replaces the
     * |install_operations|, |kernel_install_operations| and the
     * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
     * array can have more than two partitions if needed, and they are identified
     * by the partition name.
     * ```
     *
     * `repeated .chromeos_update_engine.PartitionUpdate partitions = 13;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearPartitions")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.PartitionUpdate, PartitionsProxy>.clear() {
      _builder.clearPartitions()
    }

    /**
     * ```
     * The maximum timestamp of the OS allowed to apply this payload.
     * Can be used to prevent downgrading the OS.
     * ```
     *
     * `optional int64 max_timestamp = 14;`
     */
    public var maxTimestamp: kotlin.Long
      @kotlin.jvm.JvmName("getMaxTimestamp")
        get() = _builder.maxTimestamp
      @kotlin.jvm.JvmName("setMaxTimestamp")
        set(value) {
        _builder.maxTimestamp = value
      }
    /**
     * ```
     * The maximum timestamp of the OS allowed to apply this payload.
     * Can be used to prevent downgrading the OS.
     * ```
     *
     * `optional int64 max_timestamp = 14;`
     */
    public fun clearMaxTimestamp() {
      _builder.clearMaxTimestamp()
    }
    /**
     * ```
     * The maximum timestamp of the OS allowed to apply this payload.
     * Can be used to prevent downgrading the OS.
     * ```
     *
     * `optional int64 max_timestamp = 14;`
     * @return Whether the maxTimestamp field is set.
     */
    public fun hasMaxTimestamp(): kotlin.Boolean {
      return _builder.hasMaxTimestamp()
    }

    /**
     * ```
     * Metadata related to all dynamic partitions.
     * ```
     *
     * `optional .chromeos_update_engine.DynamicPartitionMetadata dynamic_partition_metadata = 15;`
     */
    public var dynamicPartitionMetadata: chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata
      @kotlin.jvm.JvmName("getDynamicPartitionMetadata")
        get() = _builder.dynamicPartitionMetadata
      @kotlin.jvm.JvmName("setDynamicPartitionMetadata")
        set(value) {
        _builder.dynamicPartitionMetadata = value
      }
    /**
     * ```
     * Metadata related to all dynamic partitions.
     * ```
     *
     * `optional .chromeos_update_engine.DynamicPartitionMetadata dynamic_partition_metadata = 15;`
     */
    public fun clearDynamicPartitionMetadata() {
      _builder.clearDynamicPartitionMetadata()
    }
    /**
     * ```
     * Metadata related to all dynamic partitions.
     * ```
     *
     * `optional .chromeos_update_engine.DynamicPartitionMetadata dynamic_partition_metadata = 15;`
     * @return Whether the dynamicPartitionMetadata field is set.
     */
    public fun hasDynamicPartitionMetadata(): kotlin.Boolean {
      return _builder.hasDynamicPartitionMetadata()
    }

    public val DeltaArchiveManifestKt.Dsl.dynamicPartitionMetadataOrNull: chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata?
      get() = _builder.dynamicPartitionMetadataOrNull

    /**
     * ```
     * If the payload only updates a subset of partitions on the device.
     * ```
     *
     * `optional bool partial_update = 16;`
     */
    public var partialUpdate: kotlin.Boolean
      @kotlin.jvm.JvmName("getPartialUpdate")
        get() = _builder.partialUpdate
      @kotlin.jvm.JvmName("setPartialUpdate")
        set(value) {
        _builder.partialUpdate = value
      }
    /**
     * ```
     * If the payload only updates a subset of partitions on the device.
     * ```
     *
     * `optional bool partial_update = 16;`
     */
    public fun clearPartialUpdate() {
      _builder.clearPartialUpdate()
    }
    /**
     * ```
     * If the payload only updates a subset of partitions on the device.
     * ```
     *
     * `optional bool partial_update = 16;`
     * @return Whether the partialUpdate field is set.
     */
    public fun hasPartialUpdate(): kotlin.Boolean {
      return _builder.hasPartialUpdate()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ApexInfoProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Information on compressed APEX to figure out how much space is required for
     * their decompression
     * ```
     *
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 17;`
     */
     public val apexInfo: com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.apexInfoList
      )
    /**
     * ```
     * Information on compressed APEX to figure out how much space is required for
     * their decompression
     * ```
     *
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 17;`
     * @param value The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addApexInfo")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.add(value: chromeos_update_engine.UpdateMetadata.ApexInfo) {
      _builder.addApexInfo(value)
    }
    /**
     * ```
     * Information on compressed APEX to figure out how much space is required for
     * their decompression
     * ```
     *
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 17;`
     * @param value The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignApexInfo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.plusAssign(value: chromeos_update_engine.UpdateMetadata.ApexInfo) {
      add(value)
    }
    /**
     * ```
     * Information on compressed APEX to figure out how much space is required for
     * their decompression
     * ```
     *
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 17;`
     * @param values The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllApexInfo")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.addAll(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.ApexInfo>) {
      _builder.addAllApexInfo(values)
    }
    /**
     * ```
     * Information on compressed APEX to figure out how much space is required for
     * their decompression
     * ```
     *
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 17;`
     * @param values The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllApexInfo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.plusAssign(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.ApexInfo>) {
      addAll(values)
    }
    /**
     * ```
     * Information on compressed APEX to figure out how much space is required for
     * their decompression
     * ```
     *
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 17;`
     * @param index The index to set the value at.
     * @param value The apexInfo to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setApexInfo")
    public operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.set(index: kotlin.Int, value: chromeos_update_engine.UpdateMetadata.ApexInfo) {
      _builder.setApexInfo(index, value)
    }
    /**
     * ```
     * Information on compressed APEX to figure out how much space is required for
     * their decompression
     * ```
     *
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 17;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearApexInfo")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.clear() {
      _builder.clearApexInfo()
    }

    /**
     * ```
     * Security patch level of the device, usually in the format of
     * yyyy-mm-dd
     * ```
     *
     * `optional string security_patch_level = 18;`
     */
    public var securityPatchLevel: kotlin.String
      @kotlin.jvm.JvmName("getSecurityPatchLevel")
        get() = _builder.securityPatchLevel
      @kotlin.jvm.JvmName("setSecurityPatchLevel")
        set(value) {
        _builder.securityPatchLevel = value
      }
    /**
     * ```
     * Security patch level of the device, usually in the format of
     * yyyy-mm-dd
     * ```
     *
     * `optional string security_patch_level = 18;`
     */
    public fun clearSecurityPatchLevel() {
      _builder.clearSecurityPatchLevel()
    }
    /**
     * ```
     * Security patch level of the device, usually in the format of
     * yyyy-mm-dd
     * ```
     *
     * `optional string security_patch_level = 18;`
     * @return Whether the securityPatchLevel field is set.
     */
    public fun hasSecurityPatchLevel(): kotlin.Boolean {
      return _builder.hasSecurityPatchLevel()
    }
  }
}
public inline fun chromeos_update_engine.UpdateMetadata.DeltaArchiveManifest.copy(block: `chromeos_update_engine`.DeltaArchiveManifestKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.DeltaArchiveManifest =
  `chromeos_update_engine`.DeltaArchiveManifestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val chromeos_update_engine.UpdateMetadata.DeltaArchiveManifestOrBuilder.dynamicPartitionMetadataOrNull: chromeos_update_engine.UpdateMetadata.DynamicPartitionMetadata?
  get() = if (hasDynamicPartitionMetadata()) getDynamicPartitionMetadata() else null

