// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializedynamicPartitionGroup")
public inline fun dynamicPartitionGroup(block: chromeos_update_engine.DynamicPartitionGroupKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup =
  chromeos_update_engine.DynamicPartitionGroupKt.Dsl._create(chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `chromeos_update_engine.DynamicPartitionGroup`
 */
public object DynamicPartitionGroupKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup = _builder.build()

    /**
     * ```
     * Name of the group.
     * ```
     *
     * `required string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * ```
     * Name of the group.
     * ```
     *
     * `required string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * ```
     * Name of the group.
     * ```
     *
     * `required string name = 1;`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * ```
     * Maximum size of the group. The sum of sizes of all partitions in the group
     * must not exceed the maximum size of the group.
     * ```
     *
     * `optional uint64 size = 2;`
     */
    public var size: kotlin.Long
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * ```
     * Maximum size of the group. The sum of sizes of all partitions in the group
     * must not exceed the maximum size of the group.
     * ```
     *
     * `optional uint64 size = 2;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
    /**
     * ```
     * Maximum size of the group. The sum of sizes of all partitions in the group
     * must not exceed the maximum size of the group.
     * ```
     *
     * `optional uint64 size = 2;`
     * @return Whether the size field is set.
     */
    public fun hasSize(): kotlin.Boolean {
      return _builder.hasSize()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PartitionNamesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * A list of partitions that belong to the group.
     * ```
     *
     * `repeated string partition_names = 3;`
     * @return A list containing the partitionNames.
     */
    public val partitionNames: com.google.protobuf.kotlin.DslList<kotlin.String, PartitionNamesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.partitionNamesList
      )
    /**
     * ```
     * A list of partitions that belong to the group.
     * ```
     *
     * `repeated string partition_names = 3;`
     * @param value The partitionNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPartitionNames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PartitionNamesProxy>.add(value: kotlin.String) {
      _builder.addPartitionNames(value)
    }
    /**
     * ```
     * A list of partitions that belong to the group.
     * ```
     *
     * `repeated string partition_names = 3;`
     * @param value The partitionNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPartitionNames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PartitionNamesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * A list of partitions that belong to the group.
     * ```
     *
     * `repeated string partition_names = 3;`
     * @param values The partitionNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPartitionNames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PartitionNamesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPartitionNames(values)
    }
    /**
     * ```
     * A list of partitions that belong to the group.
     * ```
     *
     * `repeated string partition_names = 3;`
     * @param values The partitionNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPartitionNames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PartitionNamesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * A list of partitions that belong to the group.
     * ```
     *
     * `repeated string partition_names = 3;`
     * @param index The index to set the value at.
     * @param value The partitionNames to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPartitionNames")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PartitionNamesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPartitionNames(index, value)
    }/**
     * ```
     * A list of partitions that belong to the group.
     * ```
     *
     * `repeated string partition_names = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPartitionNames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, PartitionNamesProxy>.clear() {
      _builder.clearPartitionNames()
    }}
}
public inline fun chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup.copy(block: `chromeos_update_engine`.DynamicPartitionGroupKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.DynamicPartitionGroup =
  `chromeos_update_engine`.DynamicPartitionGroupKt.Dsl._create(this.toBuilder()).apply { block() }._build()

