// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializeinstallOperation")
public inline fun installOperation(block: chromeos_update_engine.InstallOperationKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.InstallOperation =
  chromeos_update_engine.InstallOperationKt.Dsl._create(chromeos_update_engine.UpdateMetadata.InstallOperation.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `chromeos_update_engine.InstallOperation`
 */
public object InstallOperationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.InstallOperation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.InstallOperation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.InstallOperation = _builder.build()

    /**
     * `required .chromeos_update_engine.InstallOperation.Type type = 1;`
     */
    public var type: chromeos_update_engine.UpdateMetadata.InstallOperation.Type
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * `required .chromeos_update_engine.InstallOperation.Type type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * `required .chromeos_update_engine.InstallOperation.Type type = 1;`
     * @return Whether the type field is set.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }

    /**
     * ```
     * Only minor version 6 or newer support 64 bits |data_offset| and
     * |data_length|, older client will read them as uint32.
     * The offset into the delta file (after the protobuf)
     * where the data (if any) is stored
     * ```
     *
     * `optional uint64 data_offset = 2;`
     */
    public var dataOffset: kotlin.Long
      @kotlin.jvm.JvmName("getDataOffset")
        get() = _builder.dataOffset
      @kotlin.jvm.JvmName("setDataOffset")
        set(value) {
        _builder.dataOffset = value
      }
    /**
     * ```
     * Only minor version 6 or newer support 64 bits |data_offset| and
     * |data_length|, older client will read them as uint32.
     * The offset into the delta file (after the protobuf)
     * where the data (if any) is stored
     * ```
     *
     * `optional uint64 data_offset = 2;`
     */
    public fun clearDataOffset() {
      _builder.clearDataOffset()
    }
    /**
     * ```
     * Only minor version 6 or newer support 64 bits |data_offset| and
     * |data_length|, older client will read them as uint32.
     * The offset into the delta file (after the protobuf)
     * where the data (if any) is stored
     * ```
     *
     * `optional uint64 data_offset = 2;`
     * @return Whether the dataOffset field is set.
     */
    public fun hasDataOffset(): kotlin.Boolean {
      return _builder.hasDataOffset()
    }

    /**
     * ```
     * The length of the data in the delta file
     * ```
     *
     * `optional uint64 data_length = 3;`
     */
    public var dataLength: kotlin.Long
      @kotlin.jvm.JvmName("getDataLength")
        get() = _builder.dataLength
      @kotlin.jvm.JvmName("setDataLength")
        set(value) {
        _builder.dataLength = value
      }
    /**
     * ```
     * The length of the data in the delta file
     * ```
     *
     * `optional uint64 data_length = 3;`
     */
    public fun clearDataLength() {
      _builder.clearDataLength()
    }
    /**
     * ```
     * The length of the data in the delta file
     * ```
     *
     * `optional uint64 data_length = 3;`
     * @return Whether the dataLength field is set.
     */
    public fun hasDataLength(): kotlin.Boolean {
      return _builder.hasDataLength()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SrcExtentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Ordered list of extents that are read from (if any) and written to.
     * ```
     *
     * `repeated .chromeos_update_engine.Extent src_extents = 4;`
     */
     public val srcExtents: com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, SrcExtentsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.srcExtentsList
      )
    /**
     * ```
     * Ordered list of extents that are read from (if any) and written to.
     * ```
     *
     * `repeated .chromeos_update_engine.Extent src_extents = 4;`
     * @param value The srcExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSrcExtents")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, SrcExtentsProxy>.add(value: chromeos_update_engine.UpdateMetadata.Extent) {
      _builder.addSrcExtents(value)
    }
    /**
     * ```
     * Ordered list of extents that are read from (if any) and written to.
     * ```
     *
     * `repeated .chromeos_update_engine.Extent src_extents = 4;`
     * @param value The srcExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSrcExtents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, SrcExtentsProxy>.plusAssign(value: chromeos_update_engine.UpdateMetadata.Extent) {
      add(value)
    }
    /**
     * ```
     * Ordered list of extents that are read from (if any) and written to.
     * ```
     *
     * `repeated .chromeos_update_engine.Extent src_extents = 4;`
     * @param values The srcExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSrcExtents")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, SrcExtentsProxy>.addAll(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.Extent>) {
      _builder.addAllSrcExtents(values)
    }
    /**
     * ```
     * Ordered list of extents that are read from (if any) and written to.
     * ```
     *
     * `repeated .chromeos_update_engine.Extent src_extents = 4;`
     * @param values The srcExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSrcExtents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, SrcExtentsProxy>.plusAssign(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.Extent>) {
      addAll(values)
    }
    /**
     * ```
     * Ordered list of extents that are read from (if any) and written to.
     * ```
     *
     * `repeated .chromeos_update_engine.Extent src_extents = 4;`
     * @param index The index to set the value at.
     * @param value The srcExtents to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSrcExtents")
    public operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, SrcExtentsProxy>.set(index: kotlin.Int, value: chromeos_update_engine.UpdateMetadata.Extent) {
      _builder.setSrcExtents(index, value)
    }
    /**
     * ```
     * Ordered list of extents that are read from (if any) and written to.
     * ```
     *
     * `repeated .chromeos_update_engine.Extent src_extents = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSrcExtents")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, SrcExtentsProxy>.clear() {
      _builder.clearSrcExtents()
    }

    /**
     * ```
     * Byte length of src, equal to the number of blocks in src_extents *
     * block_size. It is used for BSDIFF and SOURCE_BSDIFF, because we need to
     * pass that external program the number of bytes to read from the blocks we
     * pass it.  This is not used in any other operation.
     * ```
     *
     * `optional uint64 src_length = 5;`
     */
    public var srcLength: kotlin.Long
      @kotlin.jvm.JvmName("getSrcLength")
        get() = _builder.srcLength
      @kotlin.jvm.JvmName("setSrcLength")
        set(value) {
        _builder.srcLength = value
      }
    /**
     * ```
     * Byte length of src, equal to the number of blocks in src_extents *
     * block_size. It is used for BSDIFF and SOURCE_BSDIFF, because we need to
     * pass that external program the number of bytes to read from the blocks we
     * pass it.  This is not used in any other operation.
     * ```
     *
     * `optional uint64 src_length = 5;`
     */
    public fun clearSrcLength() {
      _builder.clearSrcLength()
    }
    /**
     * ```
     * Byte length of src, equal to the number of blocks in src_extents *
     * block_size. It is used for BSDIFF and SOURCE_BSDIFF, because we need to
     * pass that external program the number of bytes to read from the blocks we
     * pass it.  This is not used in any other operation.
     * ```
     *
     * `optional uint64 src_length = 5;`
     * @return Whether the srcLength field is set.
     */
    public fun hasSrcLength(): kotlin.Boolean {
      return _builder.hasSrcLength()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DstExtentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .chromeos_update_engine.Extent dst_extents = 6;`
     */
     public val dstExtents: com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, DstExtentsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.dstExtentsList
      )
    /**
     * `repeated .chromeos_update_engine.Extent dst_extents = 6;`
     * @param value The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addDstExtents")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, DstExtentsProxy>.add(value: chromeos_update_engine.UpdateMetadata.Extent) {
      _builder.addDstExtents(value)
    }
    /**
     * `repeated .chromeos_update_engine.Extent dst_extents = 6;`
     * @param value The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignDstExtents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, DstExtentsProxy>.plusAssign(value: chromeos_update_engine.UpdateMetadata.Extent) {
      add(value)
    }
    /**
     * `repeated .chromeos_update_engine.Extent dst_extents = 6;`
     * @param values The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllDstExtents")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, DstExtentsProxy>.addAll(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.Extent>) {
      _builder.addAllDstExtents(values)
    }
    /**
     * `repeated .chromeos_update_engine.Extent dst_extents = 6;`
     * @param values The dstExtents to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllDstExtents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, DstExtentsProxy>.plusAssign(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.Extent>) {
      addAll(values)
    }
    /**
     * `repeated .chromeos_update_engine.Extent dst_extents = 6;`
     * @param index The index to set the value at.
     * @param value The dstExtents to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDstExtents")
    public operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, DstExtentsProxy>.set(index: kotlin.Int, value: chromeos_update_engine.UpdateMetadata.Extent) {
      _builder.setDstExtents(index, value)
    }
    /**
     * `repeated .chromeos_update_engine.Extent dst_extents = 6;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDstExtents")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.Extent, DstExtentsProxy>.clear() {
      _builder.clearDstExtents()
    }

    /**
     * ```
     * Byte length of dst, equal to the number of blocks in dst_extents *
     * block_size. Used for BSDIFF and SOURCE_BSDIFF, but not in any other
     * operation.
     * ```
     *
     * `optional uint64 dst_length = 7;`
     */
    public var dstLength: kotlin.Long
      @kotlin.jvm.JvmName("getDstLength")
        get() = _builder.dstLength
      @kotlin.jvm.JvmName("setDstLength")
        set(value) {
        _builder.dstLength = value
      }
    /**
     * ```
     * Byte length of dst, equal to the number of blocks in dst_extents *
     * block_size. Used for BSDIFF and SOURCE_BSDIFF, but not in any other
     * operation.
     * ```
     *
     * `optional uint64 dst_length = 7;`
     */
    public fun clearDstLength() {
      _builder.clearDstLength()
    }
    /**
     * ```
     * Byte length of dst, equal to the number of blocks in dst_extents *
     * block_size. Used for BSDIFF and SOURCE_BSDIFF, but not in any other
     * operation.
     * ```
     *
     * `optional uint64 dst_length = 7;`
     * @return Whether the dstLength field is set.
     */
    public fun hasDstLength(): kotlin.Boolean {
      return _builder.hasDstLength()
    }

    /**
     * ```
     * Optional SHA 256 hash of the blob associated with this operation.
     * This is used as a primary validation for http-based downloads and
     * as a defense-in-depth validation for https-based downloads. If
     * the operation doesn't refer to any blob, this field will have
     * zero bytes.
     * ```
     *
     * `optional bytes data_sha256_hash = 8;`
     */
    public var dataSha256Hash: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDataSha256Hash")
        get() = _builder.dataSha256Hash
      @kotlin.jvm.JvmName("setDataSha256Hash")
        set(value) {
        _builder.dataSha256Hash = value
      }
    /**
     * ```
     * Optional SHA 256 hash of the blob associated with this operation.
     * This is used as a primary validation for http-based downloads and
     * as a defense-in-depth validation for https-based downloads. If
     * the operation doesn't refer to any blob, this field will have
     * zero bytes.
     * ```
     *
     * `optional bytes data_sha256_hash = 8;`
     */
    public fun clearDataSha256Hash() {
      _builder.clearDataSha256Hash()
    }
    /**
     * ```
     * Optional SHA 256 hash of the blob associated with this operation.
     * This is used as a primary validation for http-based downloads and
     * as a defense-in-depth validation for https-based downloads. If
     * the operation doesn't refer to any blob, this field will have
     * zero bytes.
     * ```
     *
     * `optional bytes data_sha256_hash = 8;`
     * @return Whether the dataSha256Hash field is set.
     */
    public fun hasDataSha256Hash(): kotlin.Boolean {
      return _builder.hasDataSha256Hash()
    }

    /**
     * ```
     * Indicates the SHA 256 hash of the source data referenced in src_extents at
     * the time of applying the operation. If present, the update_engine daemon
     * MUST read and verify the source data before applying the operation.
     * ```
     *
     * `optional bytes src_sha256_hash = 9;`
     */
    public var srcSha256Hash: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSrcSha256Hash")
        get() = _builder.srcSha256Hash
      @kotlin.jvm.JvmName("setSrcSha256Hash")
        set(value) {
        _builder.srcSha256Hash = value
      }
    /**
     * ```
     * Indicates the SHA 256 hash of the source data referenced in src_extents at
     * the time of applying the operation. If present, the update_engine daemon
     * MUST read and verify the source data before applying the operation.
     * ```
     *
     * `optional bytes src_sha256_hash = 9;`
     */
    public fun clearSrcSha256Hash() {
      _builder.clearSrcSha256Hash()
    }
    /**
     * ```
     * Indicates the SHA 256 hash of the source data referenced in src_extents at
     * the time of applying the operation. If present, the update_engine daemon
     * MUST read and verify the source data before applying the operation.
     * ```
     *
     * `optional bytes src_sha256_hash = 9;`
     * @return Whether the srcSha256Hash field is set.
     */
    public fun hasSrcSha256Hash(): kotlin.Boolean {
      return _builder.hasSrcSha256Hash()
    }
  }
}
public inline fun chromeos_update_engine.UpdateMetadata.InstallOperation.copy(block: `chromeos_update_engine`.InstallOperationKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.InstallOperation =
  `chromeos_update_engine`.InstallOperationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

