// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializepartitionInfo")
public inline fun partitionInfo(block: chromeos_update_engine.PartitionInfoKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.PartitionInfo =
  chromeos_update_engine.PartitionInfoKt.Dsl._create(chromeos_update_engine.UpdateMetadata.PartitionInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `chromeos_update_engine.PartitionInfo`
 */
public object PartitionInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.PartitionInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.PartitionInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.PartitionInfo = _builder.build()

    /**
     * `optional uint64 size = 1;`
     */
    public var size: kotlin.Long
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `optional uint64 size = 1;`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
    /**
     * `optional uint64 size = 1;`
     * @return Whether the size field is set.
     */
    public fun hasSize(): kotlin.Boolean {
      return _builder.hasSize()
    }

    /**
     * `optional bytes hash = 2;`
     */
    public var hash: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getHash")
        get() = _builder.hash
      @kotlin.jvm.JvmName("setHash")
        set(value) {
        _builder.hash = value
      }
    /**
     * `optional bytes hash = 2;`
     */
    public fun clearHash() {
      _builder.clearHash()
    }
    /**
     * `optional bytes hash = 2;`
     * @return Whether the hash field is set.
     */
    public fun hasHash(): kotlin.Boolean {
      return _builder.hasHash()
    }
  }
}
public inline fun chromeos_update_engine.UpdateMetadata.PartitionInfo.copy(block: `chromeos_update_engine`.PartitionInfoKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.PartitionInfo =
  `chromeos_update_engine`.PartitionInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

