// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializeapexMetadata")
public inline fun apexMetadata(block: chromeos_update_engine.ApexMetadataKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.ApexMetadata =
  chromeos_update_engine.ApexMetadataKt.Dsl._create(chromeos_update_engine.UpdateMetadata.ApexMetadata.newBuilder()).apply { block() }._build()
/**
 * ```
 * Definition has been duplicated from
 * $ANDROID_BUILD_TOP/build/tools/releasetools/ota_metadata.proto. Keep in sync.
 * ```
 *
 * Protobuf type `chromeos_update_engine.ApexMetadata`
 */
public object ApexMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.ApexMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.ApexMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.ApexMetadata = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ApexInfoProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 1;`
     */
     public val apexInfo: com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.apexInfoList
      )
    /**
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 1;`
     * @param value The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addApexInfo")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.add(value: chromeos_update_engine.UpdateMetadata.ApexInfo) {
      _builder.addApexInfo(value)
    }
    /**
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 1;`
     * @param value The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignApexInfo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.plusAssign(value: chromeos_update_engine.UpdateMetadata.ApexInfo) {
      add(value)
    }
    /**
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 1;`
     * @param values The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllApexInfo")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.addAll(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.ApexInfo>) {
      _builder.addAllApexInfo(values)
    }
    /**
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 1;`
     * @param values The apexInfo to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllApexInfo")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.plusAssign(values: kotlin.collections.Iterable<chromeos_update_engine.UpdateMetadata.ApexInfo>) {
      addAll(values)
    }
    /**
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 1;`
     * @param index The index to set the value at.
     * @param value The apexInfo to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setApexInfo")
    public operator fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.set(index: kotlin.Int, value: chromeos_update_engine.UpdateMetadata.ApexInfo) {
      _builder.setApexInfo(index, value)
    }
    /**
     * `repeated .chromeos_update_engine.ApexInfo apex_info = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearApexInfo")
    public fun com.google.protobuf.kotlin.DslList<chromeos_update_engine.UpdateMetadata.ApexInfo, ApexInfoProxy>.clear() {
      _builder.clearApexInfo()
    }
  }
}
public inline fun chromeos_update_engine.UpdateMetadata.ApexMetadata.copy(block: `chromeos_update_engine`.ApexMetadataKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.ApexMetadata =
  `chromeos_update_engine`.ApexMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

