// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializecowMergeOperation")
public inline fun cowMergeOperation(block: chromeos_update_engine.CowMergeOperationKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.CowMergeOperation =
  chromeos_update_engine.CowMergeOperationKt.Dsl._create(chromeos_update_engine.UpdateMetadata.CowMergeOperation.newBuilder()).apply { block() }._build()
/**
 * ```
 * Hints to VAB snapshot to skip writing some blocks if these blocks are
 * identical to the ones on the source image. The src & dst extents for each
 * CowMergeOperation should be contiguous, and they're a subset of an OTA
 * InstallOperation.
 * During merge time, we need to follow the pre-computed sequence to avoid
 * read after write, similar to the inplace update schema.
 * ```
 *
 * Protobuf type `chromeos_update_engine.CowMergeOperation`
 */
public object CowMergeOperationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.CowMergeOperation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.CowMergeOperation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.CowMergeOperation = _builder.build()

    /**
     * `optional .chromeos_update_engine.CowMergeOperation.Type type = 1;`
     */
    public var type: chromeos_update_engine.UpdateMetadata.CowMergeOperation.Type
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * `optional .chromeos_update_engine.CowMergeOperation.Type type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * `optional .chromeos_update_engine.CowMergeOperation.Type type = 1;`
     * @return Whether the type field is set.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }

    /**
     * `optional .chromeos_update_engine.Extent src_extent = 2;`
     */
    public var srcExtent: chromeos_update_engine.UpdateMetadata.Extent
      @kotlin.jvm.JvmName("getSrcExtent")
        get() = _builder.srcExtent
      @kotlin.jvm.JvmName("setSrcExtent")
        set(value) {
        _builder.srcExtent = value
      }
    /**
     * `optional .chromeos_update_engine.Extent src_extent = 2;`
     */
    public fun clearSrcExtent() {
      _builder.clearSrcExtent()
    }
    /**
     * `optional .chromeos_update_engine.Extent src_extent = 2;`
     * @return Whether the srcExtent field is set.
     */
    public fun hasSrcExtent(): kotlin.Boolean {
      return _builder.hasSrcExtent()
    }

    public val CowMergeOperationKt.Dsl.srcExtentOrNull: chromeos_update_engine.UpdateMetadata.Extent?
      get() = _builder.srcExtentOrNull

    /**
     * `optional .chromeos_update_engine.Extent dst_extent = 3;`
     */
    public var dstExtent: chromeos_update_engine.UpdateMetadata.Extent
      @kotlin.jvm.JvmName("getDstExtent")
        get() = _builder.dstExtent
      @kotlin.jvm.JvmName("setDstExtent")
        set(value) {
        _builder.dstExtent = value
      }
    /**
     * `optional .chromeos_update_engine.Extent dst_extent = 3;`
     */
    public fun clearDstExtent() {
      _builder.clearDstExtent()
    }
    /**
     * `optional .chromeos_update_engine.Extent dst_extent = 3;`
     * @return Whether the dstExtent field is set.
     */
    public fun hasDstExtent(): kotlin.Boolean {
      return _builder.hasDstExtent()
    }

    public val CowMergeOperationKt.Dsl.dstExtentOrNull: chromeos_update_engine.UpdateMetadata.Extent?
      get() = _builder.dstExtentOrNull

    /**
     * ```
     * For COW_XOR, source location might be unaligned, so this field is in range
     * [0, block_size), representing how much should the src_extent shift toward
     * larger block number. If this field is non-zero, then src_extent will
     * include 1 extra block in the end, as the merge op actually references the
     * first |src_offset| bytes of that extra block. For example, if |dst_extent|
     * is [10, 15], |src_offset| is 500, then src_extent might look like [25, 31].
     * Note that |src_extent| contains 1 extra block than the |dst_extent|.
     * ```
     *
     * `optional uint32 src_offset = 4;`
     */
    public var srcOffset: kotlin.Int
      @kotlin.jvm.JvmName("getSrcOffset")
        get() = _builder.srcOffset
      @kotlin.jvm.JvmName("setSrcOffset")
        set(value) {
        _builder.srcOffset = value
      }
    /**
     * ```
     * For COW_XOR, source location might be unaligned, so this field is in range
     * [0, block_size), representing how much should the src_extent shift toward
     * larger block number. If this field is non-zero, then src_extent will
     * include 1 extra block in the end, as the merge op actually references the
     * first |src_offset| bytes of that extra block. For example, if |dst_extent|
     * is [10, 15], |src_offset| is 500, then src_extent might look like [25, 31].
     * Note that |src_extent| contains 1 extra block than the |dst_extent|.
     * ```
     *
     * `optional uint32 src_offset = 4;`
     */
    public fun clearSrcOffset() {
      _builder.clearSrcOffset()
    }
    /**
     * ```
     * For COW_XOR, source location might be unaligned, so this field is in range
     * [0, block_size), representing how much should the src_extent shift toward
     * larger block number. If this field is non-zero, then src_extent will
     * include 1 extra block in the end, as the merge op actually references the
     * first |src_offset| bytes of that extra block. For example, if |dst_extent|
     * is [10, 15], |src_offset| is 500, then src_extent might look like [25, 31].
     * Note that |src_extent| contains 1 extra block than the |dst_extent|.
     * ```
     *
     * `optional uint32 src_offset = 4;`
     * @return Whether the srcOffset field is set.
     */
    public fun hasSrcOffset(): kotlin.Boolean {
      return _builder.hasSrcOffset()
    }
  }
}
public inline fun chromeos_update_engine.UpdateMetadata.CowMergeOperation.copy(block: `chromeos_update_engine`.CowMergeOperationKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.CowMergeOperation =
  `chromeos_update_engine`.CowMergeOperationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val chromeos_update_engine.UpdateMetadata.CowMergeOperationOrBuilder.srcExtentOrNull: chromeos_update_engine.UpdateMetadata.Extent?
  get() = if (hasSrcExtent()) getSrcExtent() else null

public val chromeos_update_engine.UpdateMetadata.CowMergeOperationOrBuilder.dstExtentOrNull: chromeos_update_engine.UpdateMetadata.Extent?
  get() = if (hasDstExtent()) getDstExtent() else null

