// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: update_metadata.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package chromeos_update_engine;

@kotlin.jvm.JvmName("-initializevABCFeatureSet")
public inline fun vABCFeatureSet(block: chromeos_update_engine.VABCFeatureSetKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.VABCFeatureSet =
  chromeos_update_engine.VABCFeatureSetKt.Dsl._create(chromeos_update_engine.UpdateMetadata.VABCFeatureSet.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `chromeos_update_engine.VABCFeatureSet`
 */
public object VABCFeatureSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: chromeos_update_engine.UpdateMetadata.VABCFeatureSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: chromeos_update_engine.UpdateMetadata.VABCFeatureSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): chromeos_update_engine.UpdateMetadata.VABCFeatureSet = _builder.build()

    /**
     * `optional bool threaded = 1;`
     */
    public var threaded: kotlin.Boolean
      @kotlin.jvm.JvmName("getThreaded")
        get() = _builder.threaded
      @kotlin.jvm.JvmName("setThreaded")
        set(value) {
        _builder.threaded = value
      }
    /**
     * `optional bool threaded = 1;`
     */
    public fun clearThreaded() {
      _builder.clearThreaded()
    }
    /**
     * `optional bool threaded = 1;`
     * @return Whether the threaded field is set.
     */
    public fun hasThreaded(): kotlin.Boolean {
      return _builder.hasThreaded()
    }

    /**
     * `optional bool batch_writes = 2;`
     */
    public var batchWrites: kotlin.Boolean
      @kotlin.jvm.JvmName("getBatchWrites")
        get() = _builder.batchWrites
      @kotlin.jvm.JvmName("setBatchWrites")
        set(value) {
        _builder.batchWrites = value
      }
    /**
     * `optional bool batch_writes = 2;`
     */
    public fun clearBatchWrites() {
      _builder.clearBatchWrites()
    }
    /**
     * `optional bool batch_writes = 2;`
     * @return Whether the batchWrites field is set.
     */
    public fun hasBatchWrites(): kotlin.Boolean {
      return _builder.hasBatchWrites()
    }
  }
}
public inline fun chromeos_update_engine.UpdateMetadata.VABCFeatureSet.copy(block: `chromeos_update_engine`.VABCFeatureSetKt.Dsl.() -> kotlin.Unit): chromeos_update_engine.UpdateMetadata.VABCFeatureSet =
  `chromeos_update_engine`.VABCFeatureSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

